# Generated by Django 4.2.2 on 2023-06-12 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mizobuta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangerousLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dangerous', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mizobuta.city')),
            ],
        ),
    ]
