# Generated by Django 4.2.2 on 2023-06-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mizobuta', '0002_dangerouslocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefecture',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
