# Generated by Django 4.2.2 on 2023-06-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mizobuta', '0003_prefecture_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefecture',
            name='hazardous_locations_count',
            field=models.IntegerField(default=0),
        ),
    ]
