# Generated by Django 4.2.2 on 2023-06-12 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mizobuta', '0004_prefecture_hazardous_locations_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangerouslocation',
            name='prefecture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mizobuta.prefecture'),
            preserve_default=False,
        ),
    ]
