# Generated by Django 4.2.2 on 2023-06-12 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mizobuta', '0005_dangerouslocation_prefecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dangerouslocation',
            name='city',
        ),
    ]
