# Generated by Django 4.2.2 on 2023-06-12 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mizobuta', '0006_remove_dangerouslocation_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dangerouslocation',
            name='prefecture',
        ),
        migrations.RemoveField(
            model_name='prefecture',
            name='hazardous_locations_count',
        ),
        migrations.AddField(
            model_name='dangerouslocation',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mizobuta.city'),
            preserve_default=False,
        ),
    ]
