# Generated by Django 4.2.2 on 2023-06-12 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mizobuta', '0007_remove_dangerouslocation_prefecture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazardouslocation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hazardouslocation',
            name='prefecture',
        ),
        migrations.RemoveField(
            model_name='dangerouslocation',
            name='city',
        ),
        migrations.AddField(
            model_name='dangerouslocation',
            name='prefecture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mizobuta.prefecture'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='HazardousLocation',
        ),
    ]
